### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'full_number' at row 1

### ISSUE THREAD

**Issue by phuclh** [tipoff/addresses#155]
When creating an address, got this error. Also, I selected a phone from the dropdown, it should not run the phone insertion query on the `phones` table.

<img width="1909" alt="Screen Shot 2021-05-01 at 9 52 14 AM" src="https://user-images.githubusercontent.com/6707194/116789272-e9be1e80-aa62-11eb-8156-bed37562ff57.png">

**Comment by wolfrednicolas** [comment]
@phuclh 
I'm checking this one as well, the problem looks like the var `full_number` is an object for this case

![image](https://user-images.githubusercontent.com/13080491/116790414-0584ed00-aa82-11eb-9f9c-5df58edd7f7f.png)

but there are other cases that is not an object

one solution will be... just before the firstOrCreate
                if(is_object($full_number)){
                    $full_number = $full_number->full_number;
                }
$phone = Phone::firstOrCreate(['full_number' => $full_number, 'country_callingcode_id' => 1]);

**Comment by phuclh** [comment]
@wolfrednicolas One more thing, I don't think we need to create a phone when creating an address anymore because the PhoneNumber field already takes care of that.

**Comment by wolfrednicolas** [comment]
> @wolfrednicolas One more thing, I don't think we need to create a phone when creating an address anymore because the PhoneNumber field already takes care of that.

I tested and you're right... let me remove those
