### ISSUE TITLE
Refactor Domestic and Addressables

### ISSUE THREAD

**Issue by djamesfar** [tipoff/addresses#54]
Refactor an Address model which will be polymorphic on various models (User, Company, Location), and a DomesticAddress which will have unique relations (Cart, Order, PlaceDetail, GMBDetail)

**Comment by drewroberts** [comment]
This is partly correct. Domestic Address (#19) has a one-to-many relationship with:

- Address
- Company
- Location
- Place Detail
- GMB Detail

Address is a polymorphic relationship with:

- User (Shipping & Billing)
- Order (Shipping & Billing)
- Cart (potential Shipping & Billing)

There may be other models. That will use either one of these. As you find them, ping this issue and I will let you know which one they should use. Thanks!
