### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by drewroberts** [tipoff/addresses#58]
I would like to create a phone model so that we don't have loose string fields everywhere with unformatted phone numbers that can't be verified if they even work. There are some cases that I would also like to verify a phone number so it can be sent text messages through Twilio.

Might as well default the Phone Country Code to +1 for US numbers and allow foreign phone numbers. This would then allow us to verify the Phone Area Code.

For display purposes, I want to use 407-555-5555 for US phone numbers.

**Comment by joshtorres** [comment]
This is done
