### ISSUE TITLE
Domestic Address Livewire Component

### ISSUE THREAD

**Issue by drewroberts** [tipoff/addresses#72]
I need a Livewire component with a single field for Domestic Address (#19) where a customer can start typing the address and Google Places Autocomplete (#30) is used to fill in the remainder of the address. This should then be saved with the component to the Domestic Addresses table.

**Comment by devjk1** [comment]
Do you want to use TailwindCSS for the HTML part of the Livewire component?

**Comment by drewroberts** [comment]
Yes, I'm a big fan of Tailwind. Thank you.

**Comment by devjk1** [comment]
DomesticAddressSearchBar Livewire component, the var $placesApi should be private not public.

**Comment by joshtorres** [comment]
Here are some screenshots of it working
![image](https://user-images.githubusercontent.com/5092957/115071631-81006f00-9ec4-11eb-93c3-3411685be541.png)
![image](https://user-images.githubusercontent.com/5092957/115071652-8493f600-9ec4-11eb-8739-454cd5bac92c.png)
![image](https://user-images.githubusercontent.com/5092957/115071663-88277d00-9ec4-11eb-9abc-ed4a8dfad390.png)

**Comment by drewroberts** [comment]
That looks great. Thank you!

**Comment by devjk1** [comment]
For reference, this is how to use both livewire and js versions of the components

```
<div class="flex flex-col items-center">
    <div class="w-1/2">
        <!-- Livewire version -->
        @livewire ('addresses::domestic-address-search-bar')
        <!-- JS version -->
        @include ('addresses::domestic-address-search-bar-javascript')
    </div>
    <form 
        method="POST"
        action="{{ route('your-route') }}" 
        class="w-1/2"
    >
        @csrf
        <!-- Livewire version -->
        @livewire ('addresses::domestic-address-search-bar-fields')
        <!-- JS version -->
        @include ('addresses::domestic-address-search-bar-fields-javascript')
        <button type="submit">Submit</button>
    </form>
</div>
```
