### ISSUE TITLE
Phone Livewire Component

### ISSUE THREAD

**Issue by drewroberts** [tipoff/addresses#73]
I want a Livewire component for a Phone (#58) number entry form. This will be a single field with a dropdown on the left for the Country Calling Codes (#67) that uses a flag icon or emoji for the Country (#15) and has the dropdown that looks like this:

<img width="345" alt="Screen Shot 2021-03-18 at 12 14 25 PM" src="https://user-images.githubusercontent.com/24581081/111659599-c0fc0580-87e3-11eb-845f-b40bf67d5b0b.png">

The phone number entry should allow any format and if it is a US number, then it will save it accordingly in the phones database table.

<img width="247" alt="Screen Shot 2021-03-18 at 12 14 07 PM" src="https://user-images.githubusercontent.com/24581081/111659944-015b8380-87e4-11eb-96d5-11d1072335f4.png">

Here's the article where I took these photos and it has the code for the form they created:

https://www.twilio.com/blog/international-phone-number-input-html-javascript

**Comment by drewroberts** [comment]
I don't need the Verify button after the form as in the example through that link.

**Comment by djamesfar** [comment]
The latest version of the intlTelInput javascript library referred to in the twilio link above does not work.  Had to revert to a previous version of the library.
